var express = require("express")
var cors = require("cors")
var app = express()
var bodyParser = require("body-parser")
app.use(cors())
app.use(bodyParser.json())
 var router = require("./route.js")
 app.use("/scores",router)
 app.use("/",router)
 app.listen(5000,()=>console.log("Server running at 5000"))
